<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HDC3-L-128FX5H" ignored="3" name="Regressioin" tests="18" failures="7" timestamp="2021-09-22T13:11:28 IST" time="3.404" errors="0">
  <testcase name="inValidingCustomerWithValidSecrectkey" time="1.704" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="id key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: id key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:73)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <testcase name="inValidingCustomerWithValidSecrectkey" time="1.704" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="id key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: id key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:73)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <testcase name="deleteCustomer" time="1.95" classname="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="ID key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="1.95" classname="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="ID key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="1.95" classname="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="ID key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="1.957" classname="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="ID key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="deleteCustomer" time="1.963" classname="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="ID key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase name="listAllCustomers" time="0.593" classname="com.accenture.APITestingFrameWork.testCases.GetCustomersTest"/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="0.628" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable"/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="0.653" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable"/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="0.655" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable"/>
  <testcase name="listSingleCustomer" time="0.474" classname="com.accenture.APITestingFrameWork.testCases.GetCustomersTest"/>
  <testcase name="listSingleCustomer" time="0.474" classname="com.accenture.APITestingFrameWork.testCases.GetCustomersTest"/>
  <testcase name="listSingleCustomer" time="0.485" classname="com.accenture.APITestingFrameWork.testCases.GetCustomersTest"/>
  <testcase name="listSingleCustomer" time="0.491" classname="com.accenture.APITestingFrameWork.testCases.GetCustomersTest"/>
  <testcase name="updateSingleCustomer" time="0.608" classname="com.accenture.APITestingFrameWork.testCases.UpdateCustomerTest"/>
  <testcase name="updateSingleCustomer" time="0.61" classname="com.accenture.APITestingFrameWork.testCases.UpdateCustomerTest"/>
  <testcase name="updateSingleCustomer" time="0.626" classname="com.accenture.APITestingFrameWork.testCases.UpdateCustomerTest"/>
  <testcase name="@BeforeSuite setUp" time="0.0" classname="com.accenture.APITestingFrameWork.base.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase name="@BeforeSuite setUp" time="0.0" classname="com.accenture.APITestingFrameWork.base.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase name="@BeforeSuite setUp" time="0.0" classname="com.accenture.APITestingFrameWork.base.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
</testsuite> <!-- Regressioin -->
