<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HDC3-L-128FX5H" ignored="0" name="Test" tests="5" failures="5" timestamp="2021-09-21T21:37:37 IST" time="2.206" errors="0">
  <testcase name="inValidingCustomerWithValidSecrectkey" time="1.849" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="Name key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Name key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:63)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <testcase name="inValidingCustomerWithValidSecrectkey" time="1.849" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="Name key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Name key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:63)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <testcase name="ValidingCustomerWithValidSecrectkey" time="2.115" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="Name key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Name key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.ValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:39)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- ValidingCustomerWithValidSecrectkey -->
  <testcase name="ValidingCustomerWithValidSecrectkey" time="2.115" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="Name key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Name key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.ValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:39)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- ValidingCustomerWithValidSecrectkey -->
  <testcase name="ValidingCustomerWithValidSecrectkey" time="2.115" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="Name key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Name key is not present in the Json expected [true] but found [false]
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.ValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:39)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- ValidingCustomerWithValidSecrectkey -->
</testsuite> <!-- Test -->
