<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" ignored="3" total="21" passed="11">
  <reporter-output>
  </reporter-output>
  <suite name="API TESTING" duration-ms="3404" started-at="2021-09-22T13:11:25 IST" finished-at="2021-09-22T13:11:28 IST">
    <groups>
    </groups>
    <test name="Regressioin" duration-ms="3404" started-at="2021-09-22T13:11:25 IST" finished-at="2021-09-22T13:11:28 IST">
      <class name="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable@54e1c68b]" name="setUp" is-config="true" duration-ms="388" started-at="2021-09-22T13:11:25 IST" finished-at="2021-09-22T13:11:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="inValidingCustomerWithValidSecrectkey(java.util.Hashtable)[pri:1, instance:com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable@54e1c68b]" name="inValidingCustomerWithValidSecrectkey" duration-ms="1704" started-at="2021-09-22T13:11:25 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{state=MA, name=Lia, preferred_locales2=Spanish, preferred_locales1=Englisth, phone=123456, email=Oli.Volg@gmail.com, line2=Street1, description=This is thru dp1, line1=5-4-60/1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[id key is not present in the Json expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: id key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inValidingCustomerWithValidSecrectkey -->
        <test-method status="FAIL" signature="inValidingCustomerWithValidSecrectkey(java.util.Hashtable)[pri:1, instance:com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable@54e1c68b]" name="inValidingCustomerWithValidSecrectkey" duration-ms="1704" started-at="2021-09-22T13:11:25 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{state=UP, name=sachin, preferred_locales2=Hindi, preferred_locales1=France, phone=567890, email=Tobias.wall@hotmail.com, line2=Street3, description=This is thru dp3, line1=5-4-60/3}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[id key is not present in the Json expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: id key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inValidingCustomerWithValidSecrectkey -->
        <test-method status="PASS" signature="ValidingCustomerWithValidSecrectkey(java.util.Hashtable)[pri:2, instance:com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable@54e1c68b]" name="ValidingCustomerWithValidSecrectkey" duration-ms="655" started-at="2021-09-22T13:11:27 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{state=KA, name=german, preferred_locales2=Brazil, preferred_locales1=Germany, phone=654321, email=german.Lia@gmail.com, line2=Street2, description=This is thru dp2, line1=5-4-60/2}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidingCustomerWithValidSecrectkey -->
        <test-method status="PASS" signature="ValidingCustomerWithValidSecrectkey(java.util.Hashtable)[pri:2, instance:com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable@54e1c68b]" name="ValidingCustomerWithValidSecrectkey" duration-ms="628" started-at="2021-09-22T13:11:27 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{state=UP, name=sachin, preferred_locales2=Hindi, preferred_locales1=France, phone=567890, email=sachin.suresh@hotmail.com, line2=Street3, description=This is thru dp3, line1=5-4-60/3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidingCustomerWithValidSecrectkey -->
        <test-method status="PASS" signature="ValidingCustomerWithValidSecrectkey(java.util.Hashtable)[pri:2, instance:com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable@54e1c68b]" name="ValidingCustomerWithValidSecrectkey" duration-ms="653" started-at="2021-09-22T13:11:27 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{state=MA, name=Lia, preferred_locales2=Spanish, preferred_locales1=Englisth, phone=123456, email=Lia.german@gmail.com, line2=Street1, description=This is thru dp1, line1=5-4-60/1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidingCustomerWithValidSecrectkey -->
      </class> <!-- com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable -->
      <class name="com.accenture.APITestingFrameWork.testCases.GetCustomersTest">
        <test-method status="PASS" signature="listAllCustomers()[pri:1, instance:com.accenture.APITestingFrameWork.testCases.GetCustomersTest@771a660]" name="listAllCustomers" duration-ms="593" started-at="2021-09-22T13:11:27 IST" finished-at="2021-09-22T13:11:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listAllCustomers -->
        <test-method status="PASS" signature="listSingleCustomer(java.util.Hashtable)[pri:2, instance:com.accenture.APITestingFrameWork.testCases.GetCustomersTest@771a660]" name="listSingleCustomer" duration-ms="485" started-at="2021-09-22T13:11:27 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_KGj3PrO5PpRTia}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listSingleCustomer -->
        <test-method status="PASS" signature="listSingleCustomer(java.util.Hashtable)[pri:2, instance:com.accenture.APITestingFrameWork.testCases.GetCustomersTest@771a660]" name="listSingleCustomer" duration-ms="491" started-at="2021-09-22T13:11:27 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_KGj3INOx03VAkY}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listSingleCustomer -->
        <test-method status="PASS" signature="listSingleCustomer(java.util.Hashtable)[pri:2, instance:com.accenture.APITestingFrameWork.testCases.GetCustomersTest@771a660]" name="listSingleCustomer" duration-ms="474" started-at="2021-09-22T13:11:27 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_KGj3HRyHuuBwG3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listSingleCustomer -->
        <test-method status="PASS" signature="listSingleCustomer(java.util.Hashtable)[pri:2, instance:com.accenture.APITestingFrameWork.testCases.GetCustomersTest@771a660]" name="listSingleCustomer" duration-ms="474" started-at="2021-09-22T13:11:27 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_KGjBNg4DytwUUn}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listSingleCustomer -->
      </class> <!-- com.accenture.APITestingFrameWork.testCases.GetCustomersTest -->
      <class name="com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest">
        <test-method status="FAIL" signature="deleteCustomer(java.util.Hashtable)[pri:1, instance:com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest@2d52216b]" name="deleteCustomer" duration-ms="1950" started-at="2021-09-22T13:11:25 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_KGj3PrO5PpRTia}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ID key is not present in the Json expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method status="FAIL" signature="deleteCustomer(java.util.Hashtable)[pri:1, instance:com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest@2d52216b]" name="deleteCustomer" duration-ms="1950" started-at="2021-09-22T13:11:25 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_KGixr3bEjuu2JZ}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ID key is not present in the Json expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method status="FAIL" signature="deleteCustomer(java.util.Hashtable)[pri:1, instance:com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest@2d52216b]" name="deleteCustomer" duration-ms="1963" started-at="2021-09-22T13:11:25 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_KGj3INOx03VAkY}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ID key is not present in the Json expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method status="FAIL" signature="deleteCustomer(java.util.Hashtable)[pri:1, instance:com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest@2d52216b]" name="deleteCustomer" duration-ms="1950" started-at="2021-09-22T13:11:25 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_KGj3HRyHuuBwG3}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ID key is not present in the Json expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method status="FAIL" signature="deleteCustomer(java.util.Hashtable)[pri:1, instance:com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest@2d52216b]" name="deleteCustomer" duration-ms="1957" started-at="2021-09-22T13:11:25 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_KGjBNg4DytwUUn}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ID key is not present in the Json expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ID key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
      </class> <!-- com.accenture.APITestingFrameWork.testCases.DeleteCustomerTest -->
      <class name="com.accenture.APITestingFrameWork.testCases.UpdateCustomerTest">
        <test-method status="PASS" signature="updateSingleCustomer(java.util.Hashtable)[pri:2, instance:com.accenture.APITestingFrameWork.testCases.UpdateCustomerTest@73e9cf30]" name="updateSingleCustomer" duration-ms="608" started-at="2021-09-22T13:11:28 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{state=MA, name=Lia, id=cus_KGEhFx4p2H6FlP, preferred_locales2=Spanish, preferred_locales1=Englisth, phone=123456, email=Lia.german@gmail.com, line2=Street1, description=This is thru dp1, line1=5-4-60/1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateSingleCustomer -->
        <test-method status="PASS" signature="updateSingleCustomer(java.util.Hashtable)[pri:2, instance:com.accenture.APITestingFrameWork.testCases.UpdateCustomerTest@73e9cf30]" name="updateSingleCustomer" duration-ms="610" started-at="2021-09-22T13:11:28 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{state=MA, name=Lia, id=cus_KGEhqcFhMCzca7, preferred_locales2=Spanish, preferred_locales1=Englisth, phone=123456, email=Lia.german@gmail.com, line2=Street1, description=This is thru dp1, line1=5-4-60/1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateSingleCustomer -->
        <test-method status="PASS" signature="updateSingleCustomer(java.util.Hashtable)[pri:2, instance:com.accenture.APITestingFrameWork.testCases.UpdateCustomerTest@73e9cf30]" name="updateSingleCustomer" duration-ms="626" started-at="2021-09-22T13:11:28 IST" data-provider="allTestdata" finished-at="2021-09-22T13:11:28 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{state=MA, name=Lia, id=cus_KGEhqju6ro8Uwb, preferred_locales2=Spanish, preferred_locales1=Englisth, phone=123456, email=Lia.german@gmail.com, line2=Street1, description=This is thru dp1, line1=5-4-60/1}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateSingleCustomer -->
      </class> <!-- com.accenture.APITestingFrameWork.testCases.UpdateCustomerTest -->
    </test> <!-- Regressioin -->
  </suite> <!-- API TESTING -->
</testng-results>
