<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HDC3-L-128FX5H" name="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable" tests="5" failures="2" timestamp="2021-09-22T13:11:29 IST" time="5.344" errors="0">
  <testcase name="inValidingCustomerWithValidSecrectkey" time="1.704" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="id key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: id key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <system-out/>
  <testcase name="inValidingCustomerWithValidSecrectkey" time="1.704" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable">
    <failure type="java.lang.AssertionError" message="id key is not present in the Json expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: id key is not present in the Json expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable.inValidingCustomerWithValidSecrectkey(CreateCustomerWithAllInOneSheetHashTable.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- inValidingCustomerWithValidSecrectkey -->
  <system-out/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="0.628" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable"/>
  <system-out/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="0.655" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable"/>
  <system-out/>
  <testcase name="ValidingCustomerWithValidSecrectkey" time="0.653" classname="com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable"/>
  <system-out/>
</testsuite> <!-- com.accenture.APITestingFrameWork.testCases.CreateCustomerWithAllInOneSheetHashTable -->
